### ISSUE TITLE
min/max-duration for an appointment need to be configurables

### ISSUE THREAD

**Issue by benbender** [kiebitz-oss/services-inoeg#12]
see https://github.com/kiebitz-oss/services-inoeg/blob/14064a0f5b2c123794e38d80cf206495002e6228/forms/appointments.go#L942

**Comment by benbender** [comment]
@tauli Kannst Du die beiden Variablen noch zu den Configurables hinzufügen?

 - [ ] füge appointment_duration_max/appointment_duration_min getConfigurables() hinzu
 - [ ] Interface in vanellus erweitern. see https://github.com/kiebitz-oss/vanellus-inoeg/blob/main/src/interfaces/Configurables.ts

**Comment by tauli** [comment]
done & done https://github.com/kiebitz-oss/vanellus-inoeg/commit/88bf3e3e3e16205313292e5b243024ba9efe8974

Hab aber gerade keine Ahnung warum das CI nicht durchläuft. Bei mir lokal funktioniert der Test.

**Comment by benbender** [comment]
War wohl ein caching-problem bei den images. Geht nun. closing.
