### ISSUE TITLE
Implement Mediator.getProvider(providerId)

### ISSUE THREAD

**Issue by benbender** [kiebitz-oss/services-inoeg#17]
Implement, if possible, Mediator.getProvider(providerId)-Endpoint

- [x] Implemented in Services
- [ ] Tests in Services
- [x] Implemented in Vanellus
- [x] Tests in Vanellus

_Originally posted by @benbender in https://github.com/kiebitz-oss/services-inoeg/issues/9#issuecomment-1008880942_

**Comment by benbender** [comment]
@tauli ah, irgendwie keine notification bekommen/gesehen. Ja, wäre super!

**Comment by tauli** [comment]
#25 gefixed. Tests in services erst mal zurück gestellt.

**Comment by tauli** [comment]
Guter Punkt. Hatte dafür auch schon ein Ticket erstellt https://github.com/kiebitz-oss/services-inoeg/issues/20 da können wir das sammeln
