### ISSUE TITLE
getSingleProvider()-call schlägt immer fehlt

### ISSUE THREAD

**Issue by benbender** [kiebitz-oss/services-inoeg#25]
Siehe https://github.com/kiebitz-oss/vanellus-inoeg/tree/feat/mediator-getProvider bzw im Branch vorhandene Tests. Die Signatur-verifikation schlägt scheinbar immer fehl.

Zudem müssten wir über das Feature nochmal sprechen, weil ich in `Vanellus` noch einen Weg bräuchte, zu wissen, ob der Provider `verified` true/false ist. Ggf einfach als boolean außen dran kleben, je nachdem, aus welcher DB die Response kommt.

**Comment by tauli** [comment]
fixed. siehe https://github.com/kiebitz-oss/vanellus-inoeg/pull/48
