### ISSUE TITLE
Provider.getProviderAppointments() liefert zu viele Ergebnisse zurück. 

### ISSUE THREAD

**Issue by benbender** [kiebitz-oss/services-inoeg#27]
https://github.com/kiebitz-oss/services-inoeg/commit/0f4a468c67749cad0ea9f8f7b3727c5d03bf2995#diff-c9eff54b367f9d22b13a5afccbd91bd3d2d95fc2b159bbcb830616b6268e53bfR101

**Comment by benbender** [comment]
@tauli kannst Du dafür noch nen Repro-Test schreiben? Also einfach 2-3 Appointments anlegen und checken, ob die richtige Anzahl zurückkommt.

**Comment by tauli** [comment]
test: https://github.com/kiebitz-oss/vanellus-inoeg/commit/187b50a73ea38a973ce7735f36dd5d4148c35aab
