### ISSUE TITLE
Stabile Sortierung nach Datum für abfragende Endpoints

### ISSUE THREAD

**Issue by benbender** [kiebitz-oss/services-inoeg#29]
Aktuell liefert die API Daten so aus, wie sie aus Redis kommen. Gerade wenn Limits greifen, gibt es keine Garantie, welche Daten man erhält. Aufgefallen bei `MediatorApi.getVerifiedProviders()`, `MediatorApi.getPendingProviders()`, `AnonymousApi.getAggregatedAppointments()` - betrifft aber vmtl noch mehr.

- [x] getAppointmentsAggregated
- [x] getAppointmentsByZipCode
- [x] getProviderAppointments
- [x] getProviderAppointmentsByProperty
- [x] getPendingProviders
- [x] getVerifiedProviders
- [x] getProvidersByZipCode

**Comment by tauli** [comment]
Wonach sollten Provider sortiert werden?

**Comment by benbender** [comment]
@tauli Führt zu nem anderen Problem: Eigentlich wäre für die UI sowas wie createtAt/updatedAt spannend. Aber daher wir das nicht haben, im Kern erstmal egal. Hauptsache stabil und nicht random...

**Comment by tauli** [comment]
ah ok, dann sortiere ich da nach id
