### ISSUE TITLE
getAppointmentsAggregated sollte versuchen für alle Provider Termine zu finden

### ISSUE THREAD

**Issue by tauli** [kiebitz-oss/services-inoeg#30]
Sind für einen Provider an einem bestimmten Tag keine Termine eingestellt oder bereits alle ausgebucht sollte der Endpoint versuchen weitere Termine in der Zukunft zu finden damit für jeden Provider Termine angeboten werden können.

**Comment by tauli** [comment]
Hab's jetzt so eingestellt, dass pro Provider mind. 10 Termine zurück gegeben werden. Ansonsten wird bis max. sieben Tage in die Zukunft gesucht. Außerdem filter ich jetzt noch Termine raus, die in der Vergangenheit liegen.

**Comment by benbender** [comment]
@tauli Works for me - allerdings scheint ggf. 10 ein bisschen niedrig. 25?
