### ISSUE TITLE
Endpoint to fetch configured settings?

### ISSUE THREAD

**Issue by benbender** [kiebitz-oss/services-inoeg#7]
Maybe it would be a good idea, to have a simple endpoint which only returns the configured vaccines in the instance so we can be sure to have a single source of truth between backend and ui?

**Comment by tauli** [comment]
should be fairly simple

**Comment by benbender** [comment]
I would like to extend the idea to have an endpoint, to get the configurable properties from the backend (vaccines, timespans, ...) to have them in sync :)

**Comment by tauli** [comment]
```
» curl -X GET -H "Content-Type: application/json" "http://127.0.0.1:22222/configurables" | json_pp
{
   "vaccines" : [
      "biontech",
      "moderna",
      "astrazeneca",
      "johnson-johnson"
   ],
   "anon_max_time_window" : 2,
   "provider_max_time_window" : 14
}
```
